print("hello","world")
print("hello","world",sep='$',end='&')
print("hello","world",sep='@')
print('##################')
name=input('enter your name')
age=input('enter your age')
print('hello',name)
print("your age is",age)
